kind: pipeline
name: default
workspace:
    base: /go
    path: src/github.com/fanux/cloud-kernel

# go mod vender
#environment:
#    GO111MODULE: on

# DRONE_TAG must is k8s tag, not include v
steps:
- name: build
  image: golang:1.11.3
  commands:
    - wget https://dl.k8s.io/v${DRONE_TAG}/kubernetes-server-linux-amd64.tar.gz
    - wget https://sealyun.oss-cn-beijing.aliyuncs.com/free/cloud-kernel-addon.tar.gz
    - wget https://github.com/fanux/kube/releases/download/v${DRONE_TAG}-lvscare/kubeadm
    - tar zxvf kubernetes-server-linux-amd64.tar.gz
    - tar zxvf cloud-kernel-addon.tar.gz
    - cp cloud-kernel-addon.tar kube/images/
    - cp kubeadm kube/bin/
    - cd kube
    - cp ../kubernetes/server/bin/kubectl bin/
    - cp ../kubernetes/server/bin/kubelet bin/
    - cp ../kubernetes/server/bin/kube-apiserver.tar images/
    - cp ../kubernetes/server/bin/kube-controller-manager.tar images/
    - cp ../kubernetes/server/bin/kube-scheduler.tar images/
    - cp ../kubernetes/server/bin/kube-proxy.tar images/
    - sed  "s/k8s_version/${DRONE_TAG}/g" -i conf/kubeadm.yaml
    - cd .. && tar zcvf kube${DRONE_TAG}.tar.gz kube

  when:
     event:
     - tag

- name: publish
  image: plugins/github-release
  settings:
    api_key:
        from_secret: git-release-token
    files: kube${DRONE_TAG}.tar.gz
    title: ${DRONE_TAG}
    note: Note.md
  when:
     event:
     - tag
